### PR TITLE
Sanitize file/dir parameter

### PR DESCRIPTION
**Pull request by Sjord**
Allow letters, numbers, period, comma, underscore, dash. All filenames in Doc
should be allowed, while restricting any other characters such as `<` or `;`.

### CODE REVIEW

**Comment by HazardJ** [comment]
Thanks!  If I understand correctly, this will restrict any search for a file to valid filenames.  So that a command cannot be passed disguised as a filename.  Right?  Forward slash permitted "/" ?  Or not needed?

**Comment by Sjord** [comment]
Forward slash is also permitted, but I forgot to mention it in the commit message.

So the regex is `~[^\w/.,_-]~u`:

* `~` - start of regex
* `[` - start of bracket expression. Match any letter between brackets.
* `^` - invert the match, so that all _except_ the following match.
* `\w` - all word characters, A-Z, a-z, 0-9
* `/.,_-`, literal characters. The dash `-` has to be at the end.
* `]` - end of bracket expression.
* `~` - end of regex
* `u` - interpret strings as unicode, so that `é` also matches.

**Comment by HazardJ** [comment]
BTW, the most compact and helpful description of a regex I've seen!

**Comment by dazzaji** [comment]
Almost as concise as the regex itself.

**Pull request merged**
